---
- name: for testing shell script
  hosts: all
  become: true
  tasks:
    - name: Starting Service
      debug:
       msg: Starting Httpd Service
      when: "{{ service == 'start' }}"
    - name: Starting Service
      debug:
       msg: Stoping Httpd Service
      when: "{{ service == 'stop' }}"
    - name: Stoping Service
      debug:
       msg: Restarting Httpd Service
      when: "{{ service == 'restart' }}"

      tags:
      - kafka
